DROP DATABASE IF EXISTS epimarket;
CREATE DATABASE epimarket ;
use epimarket;

CREATE TABLE CATEGORY (
NAME VARCHAR(255),
Id INT NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (Id)
);

CREATE TABLE ABSTRACTPRODUCT (
DESIGNATION VARCHAR(255),
PRICE INT,
CATEGORYID INT,
Id INT NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (Id),
FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(Id)
);

CREATE TABLE ORDERLINE (
ABSTRACTPRODUCTID INT,
QUANTITY int,
Id INT NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (Id),
FOREIGN KEY (ABSTRACTPRODUCTID) REFERENCES ABSTRACTPRODUCT(Id)
);

CREATE TABLE ADDRESS (
STREETNUMBER VARCHAR(255),
STREETNAME VARCHAR(255),
CITY VARCHAR(255),
ZIPCODE VARCHAR(255),
COUNTRY VARCHAR(255),
Id INT NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (Id)
);

CREATE TABLE CLIENT (
ADDRESSID INT,
FIRSTNAME VARCHAR(255),
LASTNAME VARCHAR(255),
Id INT NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (Id),
FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS(Id)
);

CREATE TABLE ORDERS (
CLIENTID INT,
ORDERLINEID INT,
Id INT NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (Id),
FOREIGN KEY (CLIENTID) REFERENCES CLIENT(Id)
);